[versions]
kotlin = "1.9.23"
netty = "4.1.109.Final"
rsprot = "1.0.0-ALPHA-20240629"
inlinelogger = "1.0.6"
log4j = "2.23.1"
bouncycastle = "1.70"
java-jwt = "4.4.0"
jackson = "2.17.2"
flatlaf = "3.5"
miglayout = "11.4"
clikt = "4.2.2"
classgraph = "4.8.174"
openrs2 = "0.1.0-20240627.193627-617"
swingx = "1.6.5-1"

[libraries]
netty-bom = { module = "io.netty:netty-bom", version.ref = "netty" }
netty-buffer = { module = "io.netty:netty-buffer" }
netty-transport = { module = "io.netty:netty-transport" }
netty-handler = { module = "io.netty:netty-handler" }
netty-codec-http = { module = "io.netty:netty-codec-http" }
rsprot-buffer = { module = "net.rsprot:buffer", version.ref = "rsprot" }
rsprot-compression = { module = "net.rsprot:compression", version.ref = "rsprot" }
rsprot-crypto = { module = "net.rsprot:crypto", version.ref = "rsprot" }
rsprot-protocol = { module = "net.rsprot:protocol", version.ref = "rsprot" }
log4j-bom = { module = "org.apache.logging.log4j:log4j-bom", version.ref = "log4j" }
log4j-core = { module = "org.apache.logging.log4j:log4j-core" }
log4j-api = { module = "org.apache.logging.log4j:log4j-api" }
log4j-slf4j-impl = { module = "org.apache.logging.log4j:log4j-slf4j2-impl" }
inline-logger = { module = "com.michael-bull.kotlin-inline-logger:kotlin-inline-logger", version.ref = "inlinelogger" }
bouncycastle-pkix = { module = "org.bouncycastle:bcpkix-jdk15on", version.ref = "bouncycastle" }
bouncycastle-provider = { module = "org.bouncycastle:bcprov-jdk15on", version.ref = "bouncycastle" }
java-jwt = { module = "com.auth0:java-jwt", version.ref = "java-jwt" }
jackson-annotations = { module = "com.fasterxml.jackson.core:jackson-annotations", version.ref = "jackson" }
jackson-dataformat-yaml = { module = "com.fasterxml.jackson.dataformat:jackson-dataformat-yaml", version.ref = "jackson" }
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }
flatlaf = { module = "com.formdev:flatlaf", version.ref = "flatlaf" }
flatlaf-extras = { module = "com.formdev:flatlaf-extras", version.ref = "flatlaf" }
flatlaf-intellij-themes = { module = "com.formdev:flatlaf-intellij-themes", version.ref = "flatlaf" }
mig-layout = { module = "com.miglayout:miglayout-swing", version.ref = "miglayout" }
clikt = { module = "com.github.ajalt.clikt:clikt-jvm", version.ref = "clikt" }
classgraph = { module = "io.github.classgraph:classgraph", version.ref = "classgraph" }
openrs2-buffer = { module = "org.openrs2:openrs2-buffer", version.ref = "openrs2"}
openrs2-cache = { module = "org.openrs2:openrs2-cache", version.ref = "openrs2"}
swingx = { module = "org.swinglabs.swingx:swingx-all", version.ref = "swingx" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

[bundles]
log4j = ["log4j-core", "log4j-api", "log4j-slf4j-impl", "inline-logger"]
bouncycastle = ["bouncycastle-pkix", "bouncycastle-provider"]
jackson = ["jackson-annotations", "jackson-dataformat-yaml", "jackson-module-kotlin"]
openrs2 = ["openrs2-buffer", "openrs2-cache"]
flatlaf = [ "flatlaf", "flatlaf-extras", "flatlaf-intellij-themes" ]
