package net.rsprox.shared

public enum class ScriptVarType(
    public val id: Int,
    public val char: Char,
    public val baseVarType: BaseVarType,
    private val nameOverride: String? = null,
) {
    INT(0, 'i', BaseVarType.INTEGER),
    BOOLEAN(1, '1', BaseVarType.INTEGER),
    HASH32(2, '2', BaseVarType.INTEGER),
    QUEST(3, ':', BaseVarType.INTEGER),
    QUESTHELP(4, ';', BaseVarType.INTEGER),
    CURSOR(5, '@', BaseVarType.INTEGER),
    SEQ(6, 'A', BaseVarType.INTEGER),
    COLOUR(7, 'C', BaseVarType.INTEGER),
    LOC_SHAPE(8, 'H', BaseVarType.INTEGER, "locshape"),
    COMPONENT(9, 'I', BaseVarType.INTEGER),
    IDKIT(10, 'K', BaseVarType.INTEGER),
    MIDI(11, 'M', BaseVarType.INTEGER),
    NPC_MODE(12, 'N', BaseVarType.INTEGER),
    NAMEDOBJ(13, 'O', BaseVarType.INTEGER),
    SYNTH(14, 'P', BaseVarType.INTEGER),
    AI_QUEUE(15, 'Q', BaseVarType.INTEGER),
    AREA(16, 'R', BaseVarType.INTEGER),
    STAT(17, 'S', BaseVarType.INTEGER),
    NPC_STAT(18, 'T', BaseVarType.INTEGER),
    WRITEINV(19, 'V', BaseVarType.INTEGER),
    MESH(20, '^', BaseVarType.INTEGER),
    MAPAREA(21, '`', BaseVarType.INTEGER, "wma"),
    COORDGRID(22, 'c', BaseVarType.INTEGER, "coord"),
    GRAPHIC(23, 'd', BaseVarType.INTEGER),
    CHATPHRASE(24, 'e', BaseVarType.INTEGER),
    FONTMETRICS(25, 'f', BaseVarType.INTEGER),
    ENUM(26, 'g', BaseVarType.INTEGER),
    HUNT(27, 'h', BaseVarType.INTEGER),
    JINGLE(28, 'j', BaseVarType.INTEGER),
    CHATCAT(29, 'k', BaseVarType.INTEGER),
    LOC(30, 'l', BaseVarType.INTEGER),
    MODEL(31, 'm', BaseVarType.INTEGER),
    NPC(32, 'n', BaseVarType.INTEGER),
    OBJ(33, 'o', BaseVarType.INTEGER), // namedobj
    PLAYER_UID(34, 'p', BaseVarType.INTEGER),
    REGION_UID(35, 'r', BaseVarType.LONG), // todo: this integer in osrs java client
    STRING(36, 's', BaseVarType.STRING),
    SPOTANIM(37, 't', BaseVarType.INTEGER),
    NPC_UID(38, 'u', BaseVarType.INTEGER),
    INV(39, 'v', BaseVarType.INTEGER),
    TEXTURE(40, 'x', BaseVarType.INTEGER),
    CATEGORY(41, 'y', BaseVarType.INTEGER),
    CHAR(42, 'z', BaseVarType.INTEGER),
    LASER(43, '|', BaseVarType.INTEGER),
    BAS(44, '€', BaseVarType.INTEGER),
    CONTROLLER(45, 'ƒ', BaseVarType.INTEGER),
    COLLISION_GEOMETRY(46, '‡', BaseVarType.INTEGER),
    PHYSICS_MODEL(47, '‰', BaseVarType.INTEGER),
    PHYSICS_CONTROL_MODIFIER(48, 'Š', BaseVarType.INTEGER),
    CLANHASH(49, 'Œ', BaseVarType.LONG),
    CUTSCENE(51, 'š', BaseVarType.INTEGER),
    ITEMCODE(53, '¡', BaseVarType.INTEGER),
    PVPKILLS(54, '¢', BaseVarType.INTEGER),
    MAPSCENEICON(55, '£', BaseVarType.INTEGER, "msi"),
    CLANFORUMQFC(56, '§', BaseVarType.LONG),
    VORBIS(57, '«', BaseVarType.INTEGER),
    VERIFY_OBJECT(58, '®', BaseVarType.INTEGER, "verifyobj"),
    MAPELEMENT(59, 'µ', BaseVarType.INTEGER),
    CATEGORYTYPE(60, '¶', BaseVarType.INTEGER),
    SOCIAL_NETWORK(61, 'Æ', BaseVarType.INTEGER, "socialnetwork"),
    HITMARK(62, '×', BaseVarType.INTEGER),
    PACKAGE(63, 'Þ', BaseVarType.INTEGER),
    PARTICLE_EFFECTOR(64, 'á', BaseVarType.INTEGER, "pef"),
    CONTROLLER_UID(65, 'æ', BaseVarType.INTEGER),
    PARTICLE_EMITTER(66, 'é', BaseVarType.INTEGER, "pem"),
    PLOGTYPE(67, 'í', BaseVarType.INTEGER, "plog"),
    UNSIGNED_INT(68, 'î', BaseVarType.INTEGER),
    SKYBOX(69, 'ó', BaseVarType.INTEGER),
    SKYDECOR(70, 'ú', BaseVarType.INTEGER),
    HASH64(71, 'û', BaseVarType.LONG),
    INPUTTYPE(72, 'Î', BaseVarType.INTEGER),
    STRUCT(73, 'J', BaseVarType.INTEGER),
    DBROW(74, 'Ð', BaseVarType.INTEGER),
    STORABLELABEL(75, '¤', BaseVarType.INTEGER),
    STORABLEPROC(76, '¥', BaseVarType.INTEGER),
    GAMELOGEVENT(77, 'è', BaseVarType.INTEGER),
    ANIMATIONCLIP(78, '¹', BaseVarType.INTEGER),
    SKELETON(79, '°', BaseVarType.INTEGER),
    REGIONVISIBILITY(80, 'ì', BaseVarType.INTEGER, "region_visibility"),
    FMODHANDLE(81, 'ë', BaseVarType.INTEGER),
    REGION_ALLOWLOGIN(83, 'þ', BaseVarType.INTEGER),
    REGION_INFO(84, 'ý', BaseVarType.INTEGER),
    REGION_INFO_FAILURE(85, 'ÿ', BaseVarType.INTEGER),
    SERVER_ACCOUNT_CREATION_STEP(86, 'õ', BaseVarType.INTEGER),
    CLIENT_ACCOUNT_CREATION_STEP(87, 'ô', BaseVarType.INTEGER),
    LOBBY_ACCOUNT_CREATION_STEP(88, 'ö', BaseVarType.INTEGER),
    GWC_PLATFORM(89, 'ò', BaseVarType.INTEGER, "gwc_platform"),
    CURRENCY(90, 'Ü', BaseVarType.INTEGER),
    KEYBOARD_KEY(91, 'ù', BaseVarType.INTEGER),
    MOUSEEVENT(92, 'ï', BaseVarType.INTEGER),
    HEADBAR(93, '¯', BaseVarType.INTEGER),
    BUG_TEMPLATE(94, 'ê', BaseVarType.INTEGER, "bugtemplate"),
    BILLING_AUTH_FLAG(95, 'ð', BaseVarType.INTEGER, "billingauthflag"),
    ACCOUNT_FEATURE_FLAG(96, 'å', BaseVarType.INTEGER, "accountfeatureflag"),
    INTERFACE(97, 'a', BaseVarType.INTEGER),
    TOPLEVELINTERFACE(98, 'F', BaseVarType.INTEGER),
    OVERLAYINTERFACE(99, 'L', BaseVarType.INTEGER),
    CLIENTINTERFACE(100, '©', BaseVarType.INTEGER),
    MOVESPEED(101, 'Ý', BaseVarType.INTEGER),
    MATERIAL(102, '¬', BaseVarType.INTEGER),
    SEQGROUP(103, 'ø', BaseVarType.INTEGER),
    TEMP_HISCORE(104, 'ä', BaseVarType.INTEGER, "temphiscore"),
    TEMP_HISCORE_LENGTH_TYPE(105, 'ã', BaseVarType.INTEGER, "temphiscorelengthtype"),
    TEMP_HISCORE_DISPLAY_TYPE(106, 'â', BaseVarType.INTEGER, "temphiscoretype"),
    TEMP_HISCORE_CONTRIBUTE_RESULT(107, 'à', BaseVarType.INTEGER, "temphiscorecontributeresult"),
    AUDIOGROUP(108, 'À', BaseVarType.INTEGER),
    AUDIOMIXBUSS(109, 'Ò', BaseVarType.INTEGER, "audiobuss"),
    LONG(110, 'Ï', BaseVarType.LONG),
    CRM_CHANNEL(111, 'Ì', BaseVarType.INTEGER),
    HTTP_IMAGE(112, 'É', BaseVarType.INTEGER),
    POP_UP_DISPLAY_BEHAVIOUR(113, 'Ê', BaseVarType.INTEGER, "popupdisplaybehaviour"),
    POLL(114, '÷', BaseVarType.INTEGER),
    MTXN_PACKAGE(115, '¼', BaseVarType.LONG),
    MTXN_PRICE_POINT(116, '½', BaseVarType.LONG),
    ENTITYOVERLAY(117, '-', BaseVarType.INTEGER),
    DBTABLE(118, 'Ø', BaseVarType.INTEGER),
    STRINGVECTOR(-1, '¸', BaseVarType.INTEGER),
    ;

    public val fullName: String
        get() = nameOverride ?: name.lowercase()
}
