package net.rsprox.transcriber

public enum class ScriptVarType(
    public val char: Char,
    public val fullName: String,
) {
    INTEGER('i', "integer"),
    BOOLEAN('1', "boolean"),
    SEQ('A', "seq"),
    COLOUR('C', "colour"),
    LOC_SHAPE('H', "locshape"),
    COMPONENT('I', "component"),
    IDKIT('K', "idkit"),
    MIDI('M', "midi"),
    NAMEDOBJ('O', "namedobj"),
    SYNTH('P', "synth"),
    STAT('S', "stat"),
    COORDGRID('c', "coordgrid"),
    GRAPHIC('d', "graphic"),
    FONTMETRICS('f', "fontmetrics"),
    ENUM('g', "enum"),
    JINGLE('j', "jingle"),
    LOC('l', "loc"),
    MODEL('m', "model"),
    NPC('n', "npc"),
    OBJ('o', "obj"),
    STRING('s', "string"),
    SPOTANIM('t', "spotanim"),
    INV('v', "inv"),
    TEXTURE('x', "texture"),
    CHAR('z', "char"),
    MAPSCENEICON('£', "mapsceneicon"),
    MAPELEMENT('µ', "mapelement"),
    HITMARK('×', "hitmark"),
    STRUCT('J', "struct"),
    DBROW('Ð', "dbrow"),
}
