@file:Suppress("ktlint:standard:no-wildcard-imports")

package net.rsprox.shared.filters

import net.rsprox.shared.StreamDirection
import net.rsprox.shared.StreamDirection.CLIENT_TO_SERVER
import net.rsprox.shared.StreamDirection.SERVER_TO_CLIENT
import net.rsprox.shared.filters.ProtCategory.*

@Suppress("SpellCheckingInspection")
public enum class PropertyFilter(
    public val direction: StreamDirection,
    public val category: ProtCategory,
    public val label: String,
    public val enabled: Boolean,
    public val tooltip: String? = null,
    public val searchTerms: String,
) {
    IF_BUTTON(
        CLIENT_TO_SERVER,
        INTERFACES,
        "Interface Buttons",
        true,
        searchTerms = "if,interface,ifbutton,buttons,clicks",
    ),
    IF_BUTTOND(
        CLIENT_TO_SERVER,
        INTERFACES,
        "Interface Dragging",
        false,
        searchTerms = "if,interface,ifbuttond,buttons,dragging",
    ),
    IF_BUTTONT(
        CLIENT_TO_SERVER,
        INTERFACES,
        "Interface Targetting",
        true,
        searchTerms = "if,interface,ifbuttont,buttons,targetting,use,using",
    ),
    IF_RUNSCRIPT(
        CLIENT_TO_SERVER,
        INTERFACES,
        "Interface Scripts",
        true,
        searchTerms = "if,interface,ifrunscript,scripts,serverscript,clientscript,cs2,rs2",
    ),

    OPNPC(
        CLIENT_TO_SERVER,
        NPCS,
        "Npc Clicks",
        true,
        searchTerms = "opnpc,interacting,click",
    ),
    OPNPCT(
        CLIENT_TO_SERVER,
        NPCS,
        "Npc Targetting",
        true,
        searchTerms = "opnpct,interacting,useonnpc,targetting,using",
    ),

    OPLOC(
        CLIENT_TO_SERVER,
        LOCS,
        "Loc Clicks",
        true,
        searchTerms = "oploc,interacting,objects,clicks",
    ),
    OPLOCT(
        CLIENT_TO_SERVER,
        LOCS,
        "Loc Targetting",
        true,
        searchTerms = "oploct,interacting,useonloc,targetting,using,objects",
    ),

    OPOBJ(
        CLIENT_TO_SERVER,
        OBJS,
        "Obj Clicks",
        true,
        searchTerms = "opobj,interacting,clicks,items,objects",
    ),
    OPOBJT(
        CLIENT_TO_SERVER,
        OBJS,
        "Obj Targetting",
        true,
        searchTerms = "opobjt,interacting,useonobj,useonitems,using,targetting,objects",
    ),

    OPPLAYER(
        CLIENT_TO_SERVER,
        PLAYERS,
        "Player Clicks",
        true,
        searchTerms = "opplayer,interacting,clicks,players",
    ),
    OPPLAYERT(
        CLIENT_TO_SERVER,
        PLAYERS,
        "Player Targetting",
        true,
        searchTerms = "opplayert,interacting,useonplayer,using,targetting,players",
    ),
    OPWORLDENTITY(
        CLIENT_TO_SERVER,
        WORLD_ENTITIES,
        "World Entity Clicks",
        true,
        searchTerms = "opworldentity,interacting,click",
    ),
    OPWORLDENTITYT(
        CLIENT_TO_SERVER,
        WORLD_ENTITIES,
        "World Entity Targetting",
        true,
        searchTerms = "opworldentityt,interacting,useonworldentity,targetting,using",
    ),

    EVENT_APPLET_FOCUS(
        CLIENT_TO_SERVER,
        EVENTS,
        "Applet Focus",
        false,
        searchTerms = "events,applet,focus",
    ),
    EVENT_CAMERA_POSITION(
        CLIENT_TO_SERVER,
        EVENTS,
        "Camera Position",
        false,
        searchTerms = "events,camera,position",
    ),
    EVENT_KEYBOARD(
        CLIENT_TO_SERVER,
        EVENTS,
        "Keyboard",
        false,
        searchTerms = "events,keyboard,typing,character",
    ),
    EVENT_MOUSE_SCROLL(
        CLIENT_TO_SERVER,
        EVENTS,
        "Mouse Scroll",
        false,
        searchTerms = "events,mouse,scrolling",
    ),
    EVENT_MOUSE_MOVE(
        CLIENT_TO_SERVER,
        EVENTS,
        "Mouse Movement",
        false,
        searchTerms = "events,mouse,moving",
    ),
    EVENT_NATIVE_MOUSE_MOVE(
        CLIENT_TO_SERVER,
        EVENTS,
        "Native Mouse Movement",
        false,
        searchTerms = "events,native,mouse,moving",
    ),
    EVENT_MOUSE_CLICK(
        CLIENT_TO_SERVER,
        EVENTS,
        "Mouse Click",
        false,
        searchTerms = "events,mouse,clicking,clicks",
    ),
    EVENT_NATIVE_MOUSE_CLICK(
        CLIENT_TO_SERVER,
        EVENTS,
        "Native Mouse Click",
        false,
        searchTerms = "events,native,mouse,clicking,clicks",
    ),

    RESUME_PAUSEBUTTON(
        CLIENT_TO_SERVER,
        PROT_RESUME,
        "Pausebutton",
        true,
        searchTerms = "resume,protected,access,pausebutton,dialogue",
    ),
    RESUME_P_NAMEDIALOG(
        CLIENT_TO_SERVER,
        PROT_RESUME,
        "Name Dialog",
        true,
        searchTerms = "resume,protected,access,namedialog,dialogue",
    ),
    RESUME_P_STRINGDIALOG(
        CLIENT_TO_SERVER,
        PROT_RESUME,
        "String Dialog",
        true,
        searchTerms = "resume,protected,access,stringdialog,dialogue",
    ),
    RESUME_P_COUNTDIALOG(
        CLIENT_TO_SERVER,
        PROT_RESUME,
        "Count Dialog",
        true,
        searchTerms = "resume,protected,access,count,inputint,dialogue,number,integer",
    ),
    RESUME_P_OBJDIALOG(
        CLIENT_TO_SERVER,
        PROT_RESUME,
        "Obj Dialog",
        true,
        searchTerms = "resume,protected,access,objdialog,dialogue,itemdialogue,items",
    ),

    FRIENDCHAT_KICK(
        CLIENT_TO_SERVER,
        FRIENDCHAT,
        "Friend Chat Kick",
        false,
        searchTerms = "friendchat,kick,social",
    ),
    FRIENDCHAT_SETRANK(
        CLIENT_TO_SERVER,
        FRIENDCHAT,
        "Friend Chat Ranks",
        false,
        searchTerms = "friendchat,ranks,social",
    ),
    FRIENDCHAT_JOIN_LEAVE(
        CLIENT_TO_SERVER,
        FRIENDCHAT,
        "Friend Chat Join/Leave",
        false,
        searchTerms = "friendchat,join,leave,joining,leaving,social",
    ),

    CLANCHANNEL_FULL_REQUEST(
        CLIENT_TO_SERVER,
        CLAN,
        "Clan Channel Requests",
        false,
        searchTerms = "clanchannel,clanchat,requests,social",
    ),
    CLANSETTINGS_FULL_REQUEST(
        CLIENT_TO_SERVER,
        CLAN,
        "Clan Settings Requests",
        false,
        searchTerms = "clanchannel,settings,clansettings,requests,social",
    ),
    CLANCHANNEL_KICKUSER(
        CLIENT_TO_SERVER,
        CLAN,
        "Clan Member Kicking",
        false,
        searchTerms = "clan,member,kicking,clanchannel,user,kickuser,social",
    ),
    AFFINEDCLANSETTINGS_ADDBANNED_FROMCHANNEL(
        CLIENT_TO_SERVER,
        CLAN,
        "Clan Member Banning",
        false,
        searchTerms = "clan,member,banning,banned,affined,clansettings,channel,clanchannel,social",
    ),
    AFFINEDCLANSETTINGS_SETMUTED_FROMCHANNEL(
        CLIENT_TO_SERVER,
        CLAN,
        "Clan Member Muting",
        false,
        searchTerms = "clan,member,muting,muted,affined,clansettings,channel,clanchannel,social",
    ),

    FRIENDLIST_ADD(
        CLIENT_TO_SERVER,
        SOCIAL,
        "Friendlist Add",
        false,
        searchTerms = "friendlist,add,pm,dm,social",
    ),
    FRIENDLIST_DEL(
        CLIENT_TO_SERVER,
        SOCIAL,
        "Friendlist Delete",
        false,
        searchTerms = "friendlist,delete,remove,pm,dm,social",
    ),
    IGNORELIST_ADD(
        CLIENT_TO_SERVER,
        SOCIAL,
        "Ignorelist Add",
        false,
        searchTerms = "ignorelist,add,social",
    ),
    IGNORELIST_DEL(
        CLIENT_TO_SERVER,
        SOCIAL,
        "Ignorelist Delete",
        false,
        searchTerms = "ignorelist,delete,remove,social",
    ),

    MESSAGE_PUBLIC(
        CLIENT_TO_SERVER,
        MESSAGING,
        "Public Messages",
        true,
        searchTerms = "message,public,messaging,social,chat",
    ),
    MESSAGE_PRIVATE_CLIENT(
        CLIENT_TO_SERVER,
        MESSAGING,
        "Private Messages",
        false,
        searchTerms = "message,private,pm,dm,messaging,social,chat",
    ),

    MOVE_GAMECLICK(
        CLIENT_TO_SERVER,
        OTHER,
        "Game Movement",
        false,
        searchTerms = "movegameclick,moving,walking,running,game",
    ),
    MOVE_MINIMAPCLICK(
        CLIENT_TO_SERVER,
        OTHER,
        "Minimap Movement",
        false,
        searchTerms = "moveminimapclick,moving,walking,running,minimap",
    ),
    CLIENT_CHEAT(
        CLIENT_TO_SERVER,
        OTHER,
        "Commands",
        false,
        searchTerms = "client,cheat,commands,::,;;",
    ),
    SET_CHATFILTERSETTINGS(
        CLIENT_TO_SERVER,
        OTHER,
        "Chat Filters",
        false,
        searchTerms = "chatfiltersettings,filters,chat,public,trade,private,game",
    ),
    CLICKWORLDMAP(
        CLIENT_TO_SERVER,
        OTHER,
        "Worldmap Hints",
        false,
        searchTerms = "worldmap,hints,clickworldmap",
    ),
    OCULUS_LEAVE(
        CLIENT_TO_SERVER,
        OTHER,
        "Oculus Leaving",
        false,
        searchTerms = "orb,of,oculus,leave,leaving",
    ),
    CLOSE_MODAL(
        CLIENT_TO_SERVER,
        OTHER,
        "Modal Closing",
        false,
        searchTerms = "modal,close,closing,interfaces,central",
    ),
    TELEPORT(
        CLIENT_TO_SERVER,
        OTHER,
        "Teleport Requests",
        false,
        searchTerms = "teleport,request,ctrl,shift,click",
    ),
    BUG_REPORT(
        CLIENT_TO_SERVER,
        OTHER,
        "Bug Reports",
        false,
        searchTerms = "bugs,reports,reporting",
    ),
    SEND_SNAPSHOT(
        CLIENT_TO_SERVER,
        OTHER,
        "Player Reports",
        false,
        searchTerms = "player,reporting,abuse,abusing,snapshot,send",
    ),
    HISCORE_REQUEST(
        CLIENT_TO_SERVER,
        OTHER,
        "Hiscore Requests",
        false,
        searchTerms = "hiscore,highscore,request,lookup",
    ),
    IF_CRMVIEW_CLICK(
        CLIENT_TO_SERVER,
        OTHER,
        "CRM Clicks",
        true,
        searchTerms = "interfaces,if,button,crm,content,recommendation,click",
    ),

    CONNECTION_TELEMETRY(
        CLIENT_TO_SERVER,
        OTHER,
        "Connection Telemetry",
        false,
        searchTerms = "timings,connection,telemetry,fps,ping,gc,percentage",
    ),
    SEND_PING_REPLY(
        CLIENT_TO_SERVER,
        OTHER,
        "Ping Reply",
        false,
        searchTerms = "ping,reply,telemetry,connection,timings",
    ),
    DETECT_MODIFIED_CLIENT(
        CLIENT_TO_SERVER,
        OTHER,
        "Detect Modified Client",
        false,
        searchTerms = "detect,modified,clients,modify,detection,1057001181,0x3f008edd",
    ),
    REFLECTION_CHECK_REPLY(
        CLIENT_TO_SERVER,
        OTHER,
        "Reflection Reply",
        false,
        searchTerms = "reflection,checks,java,reply,replies,checking",
    ),
    NO_TIMEOUT(
        CLIENT_TO_SERVER,
        OTHER,
        "No Timeout",
        false,
        searchTerms = "no,timeout,notimeout,timing,out,connection,lost",
    ),
    IDLE(
        CLIENT_TO_SERVER,
        OTHER,
        "Idle",
        false,
        searchTerms = "idle,idling,logout,logging,kicked",
    ),
    MAP_BUILD_COMPLETE(
        CLIENT_TO_SERVER,
        OTHER,
        "Map Build Complete",
        false,
        searchTerms = "map,build,complete,rebuild,normal,region,loaddelay",
    ),
    MEMBERSHIP_PROMOTION_ELIGIBILITY(
        CLIENT_TO_SERVER,
        OTHER,
        "Membership Promo Eligibility",
        false,
        searchTerms = "membership,membrers,promotion,eligibility,native",
    ),
    SOUND_JINGLEEND(
        CLIENT_TO_SERVER,
        OTHER,
        "Jingle End",
        false,
        searchTerms = "jingle,music,sound,ending,stopping",
    ),
    WINDOW_STATUS(
        CLIENT_TO_SERVER,
        OTHER,
        "Window Status",
        false,
        searchTerms = "window,status,width,height,mode",
    ),
    SET_HEADING(
        CLIENT_TO_SERVER,
        OTHER,
        "Set Heading",
        false,
        searchTerms = "setheading,worldentity,ship,direction",
    ),
    RSEVEN_STATUS(
        CLIENT_TO_SERVER,
        OTHER,
        "RT7 Status",
        true,
        searchTerms = "rseven,rt7,r7,status,ehc,enhanced client,native client",
    ),

    IF_RESYNC(
        SERVER_TO_CLIENT,
        INTERFACES,
        "Interface Resync",
        false,
        searchTerms = "if,resync,interfaces,synchronization,login,reload,resend",
    ),
    IF_OPENTOP(
        SERVER_TO_CLIENT,
        INTERFACES,
        "Top Open",
        true,
        searchTerms = "interfaces,open,toplevel,if,opentop",
    ),
    IF_OPENSUB(
        SERVER_TO_CLIENT,
        INTERFACES,
        "Sub Open",
        true,
        searchTerms = "interfaces,open,sublevel,if,opensub",
    ),
    IF_CLOSESUB(
        SERVER_TO_CLIENT,
        INTERFACES,
        "Sub Close",
        true,
        searchTerms = "interfaces,close,closing,sublevel,if,closesub",
    ),
    IF_MOVESUB(
        SERVER_TO_CLIENT,
        INTERFACES,
        "Sub Move",
        true,
        searchTerms = "interfaces,move,moving,sublevel,if,movesub",
    ),
    IF_CLEARINV(
        SERVER_TO_CLIENT,
        INTERFACES,
        "Clear Inventories",
        true,
        searchTerms = "interfaces,clear,inventories,if1,clearinv,inventory",
    ),
    IF_SETEVENTS(
        SERVER_TO_CLIENT,
        INTERFACES,
        "Events",
        true,
        searchTerms = "interfaces,serveractive,events,if,setevents,accessmask,button,drag,depth,use,target",
    ),
    IF_SETPOSITION(
        SERVER_TO_CLIENT,
        INTERFACES,
        "Position",
        true,
        searchTerms = "interfaces,set,position,setposition,if",
    ),
    IF_SETSCROLLPOS(
        SERVER_TO_CLIENT,
        INTERFACES,
        "Scroll Position",
        true,
        searchTerms = "interfaces,set,scroll,position,setscrollpos,scrolling,scollbar,if",
    ),
    IF_SETROTATESPEED(
        SERVER_TO_CLIENT,
        INTERFACES,
        "Rotate Speed",
        true,
        searchTerms = "interfaces,set,rotate,rotation,speed,setrotatespeed,if",
    ),
    IF_SETTEXT(
        SERVER_TO_CLIENT,
        INTERFACES,
        "Text",
        true,
        searchTerms = "interfaces,set,text,settext,string,if",
    ),
    IF_SETHIDE(
        SERVER_TO_CLIENT,
        INTERFACES,
        "Hide",
        true,
        searchTerms = "interfaces,set,hide,hiding,visible,invisible,visibility,if",
    ),
    IF_SETANGLE(
        SERVER_TO_CLIENT,
        INTERFACES,
        "Angle",
        true,
        searchTerms = "interfaces,set,angle,setangle,if",
    ),
    IF_SETOBJECT(
        SERVER_TO_CLIENT,
        INTERFACES,
        "Object",
        true,
        searchTerms = "interfaces,set,objects,setobject,items,if",
    ),
    IF_SETCOLOUR(
        SERVER_TO_CLIENT,
        INTERFACES,
        "Colour",
        true,
        searchTerms = "interfaces,set,color,colour,setcolor,setcolour,rgb,0x,if",
    ),
    IF_SETANIM(
        SERVER_TO_CLIENT,
        INTERFACES,
        "Anim",
        true,
        searchTerms = "interfaces,set,anims,sequence,setanim,animation,if",
    ),
    IF_SETNPCHEAD(
        SERVER_TO_CLIENT,
        INTERFACES,
        "Npc Head",
        true,
        searchTerms = "interfaces,set,npc,head,setnpchead,if,chatbox,dialogue",
    ),
    IF_SETNPCHEAD_ACTIVE(
        SERVER_TO_CLIENT,
        INTERFACES,
        "Npc Head Active",
        true,
        searchTerms = "interfaces,set,npc,head,active,setnpcheadactive,if,chatbox,dialogue",
    ),
    IF_SETPLAYERHEAD(
        SERVER_TO_CLIENT,
        INTERFACES,
        "Player Head",
        true,
        searchTerms = "interfaces,set,player,head,setplayerhead,if,chatbox,dialogue,self",
    ),
    IF_SETMODEL(
        SERVER_TO_CLIENT,
        INTERFACES,
        "Model",
        true,
        searchTerms = "interfaces,set,model,setmodel,if,mesh,3d",
    ),
    IF_SETPLAYERMODEL(
        SERVER_TO_CLIENT,
        INTERFACES,
        "Player Model",
        true,
        searchTerms = "interfaces,set,player,model,self,mesh,3d,if",
    ),

    MIDI_SONG(
        SERVER_TO_CLIENT,
        MIDI,
        "Midi Song",
        true,
        searchTerms = "music,song,midi,play,track,patch,sample",
    ),
    MIDI_SWAP(
        SERVER_TO_CLIENT,
        MIDI,
        "Midi Swap",
        true,
        searchTerms = "music,song,midi,play,track,patch,sample,swap",
    ),
    MIDI_SONG_STOP(
        SERVER_TO_CLIENT,
        MIDI,
        "Midi Stop",
        true,
        searchTerms = "music,song,midi,stop,track,patch,sample",
    ),
    MIDI_JINGLE(
        SERVER_TO_CLIENT,
        MIDI,
        "Jingle",
        true,
        searchTerms = "music,song,midi,jingle,play,track,patch,sample",
    ),
    SYNTH_SOUND(
        SERVER_TO_CLIENT,
        MIDI,
        "Synth",
        true,
        searchTerms = "music,song,midi,play,track,patch,sample,synth,soundeffects",
    ),

    ZONE_HEADER(
        SERVER_TO_CLIENT,
        ZONES,
        "Zone Header",
        false,
        searchTerms = "zone,chunk,header,update,full,follows,partial,enclosed",
    ),
    LOC_ADD_CHANGE(
        SERVER_TO_CLIENT,
        ZONES,
        "Loc Add Change",
        true,
        searchTerms = "loc,add,change,objects,spawn,replace,replacing,zone",
    ),
    LOC_DEL(
        SERVER_TO_CLIENT,
        ZONES,
        "Loc Del",
        true,
        searchTerms = "loc,del,delete,remove,despawn,erase,objects,zone",
    ),
    LOC_ANIM(
        SERVER_TO_CLIENT,
        ZONES,
        "Loc Anim",
        true,
        searchTerms = "loc,animation,sequence,objects,zone",
    ),
    LOC_MERGE(
        SERVER_TO_CLIENT,
        ZONES,
        "Loc Merge",
        true,
        searchTerms = "loc,merge,player,clipping,objects,self,agility,zone",
    ),
    OBJ_ADD(
        SERVER_TO_CLIENT,
        ZONES,
        "Obj Add",
        true,
        searchTerms = "objs,add,spawning,items,adding,zone",
    ),
    OBJ_DEL(
        SERVER_TO_CLIENT,
        ZONES,
        "Obj Del",
        true,
        searchTerms = "objs,del,despawning,items,removing,remove,zone",
    ),
    OBJ_COUNT(
        SERVER_TO_CLIENT,
        ZONES,
        "Obj Count",
        true,
        searchTerms = "objs,count,update,amount,quantity,items,zone",
    ),
    OBJ_ENABLED_OPS(
        SERVER_TO_CLIENT,
        ZONES,
        "Obj Enabled Ops",
        true,
        searchTerms = "objs,enabled,ops,click,options,take,taking,items,zone",
    ),
    OBJ_CUSTOMISE(
        SERVER_TO_CLIENT,
        ZONES,
        "Obj Customise",
        true,
        searchTerms = "objs,customise,model,recolour,recolor,retexture,zone,items",
    ),
    MAP_ANIM(
        SERVER_TO_CLIENT,
        ZONES,
        "Map Anim",
        true,
        searchTerms = "map,animation,sequence,gfx,graphics,tile,spotanim,mapanim,zone",
    ),
    MAP_PROJANIM(
        SERVER_TO_CLIENT,
        ZONES,
        "Map Proj Anim",
        true,
        searchTerms = "map,projanim,sequence,animation,projectiles,arrow,spell,zone",
    ),
    SOUND_AREA(
        SERVER_TO_CLIENT,
        ZONES,
        "Area Sound",
        true,
        searchTerms = "sound,midi,song,music,area,tile,zone,synth",
    ),

    PROJANIM_SPECIFIC(
        SERVER_TO_CLIENT,
        SPECIFIC,
        "Projectiles",
        true,
        searchTerms = "map,projanim,sequence,animation,projectiles,arrow,spell,zone,specifics",
    ),
    MAP_ANIM_SPECIFIC(
        SERVER_TO_CLIENT,
        SPECIFIC,
        "Map Anims",
        true,
        searchTerms = "map,animation,sequence,gfx,graphics,tile,spotanim,mapanim,zone,specifics",
    ),
    LOC_ANIM_SPECIFIC(
        SERVER_TO_CLIENT,
        SPECIFIC,
        "Loc Anims",
        true,
        searchTerms = "loc,animation,sequence,objects,zone,specifics",
    ),
    NPC_HEADICON_SPECIFIC(
        SERVER_TO_CLIENT,
        SPECIFIC,
        "Npc Head Icons",
        true,
        searchTerms = "npcs,headicons,overhead,prayer,specifics",
    ),
    NPC_SPOTANIM_SPECIFIC(
        SERVER_TO_CLIENT,
        SPECIFIC,
        "Npc Spotanims",
        true,
        searchTerms = "npcs,spotanim,gfx,graphics,specifics",
    ),
    NPC_ANIM_SPECIFIC(
        SERVER_TO_CLIENT,
        SPECIFIC,
        "Npc Anims",
        true,
        searchTerms = "npcs,anim,animations,sequences,specifics",
    ),
    PLAYER_ANIM_SPECIFIC(
        SERVER_TO_CLIENT,
        SPECIFIC,
        "Player Anims",
        true,
        searchTerms = "players,self,animations,sequences,specifics",
    ),
    PLAYER_SPOTANIM_SPECIFIC(
        SERVER_TO_CLIENT,
        SPECIFIC,
        "Player Spotanims",
        true,
        searchTerms = "player,spotanim,gfx,graphics,specifics",
    ),

    PLAYER_INFO(
        SERVER_TO_CLIENT,
        INFO,
        "Player Info",
        true,
        searchTerms = "player,info,update,updating,crawling,walking,running,teleporting,players",
    ),
    PLAYER_ADD(
        SERVER_TO_CLIENT,
        INFO,
        "Player Add",
        true,
        tooltip = "Logs an entry about a player that was just added to high resolution.",
        searchTerms = "player,info,update,updating,add,adding",
    ),
    PLAYER_DEL(
        SERVER_TO_CLIENT,
        INFO,
        "Player Delete",
        true,
        tooltip = "Logs an entry about a player that was just deleted from high resolution.",
        searchTerms = "player,info,update,updating,del,deleting,remove,removing",
    ),
    PLAYER_MOVEMENT(
        SERVER_TO_CLIENT,
        INFO,
        "Player Movement",
        true,
        tooltip = "Logs an entry about a player that just crawled, walked, ran or teleported.",
        searchTerms = "player,info,update,updating,movement,crawling,walking,running,ran,teleport",
    ),
    PLAYER_EXT_INFO(
        SERVER_TO_CLIENT,
        INFO,
        "Player Ext. Info",
        true,
        tooltip = "Logs an entry about a player that had an extended info applied to them.",
        searchTerms = "player,info,update,updating,extended,info,updating,masks",
    ),
    NPC_INFO(
        SERVER_TO_CLIENT,
        INFO,
        "Npc Info",
        true,
        searchTerms = "npc,info,updating,npcs,update,",
    ),
    NPC_ADD(
        SERVER_TO_CLIENT,
        INFO,
        "Npc Add",
        true,
        tooltip = "Logs an entry about a NPC that was just added to high resolution.",
        searchTerms = "npc,info,updating,npcs,update,add,adding",
    ),
    NPC_DEL(
        SERVER_TO_CLIENT,
        INFO,
        "Npc Delete",
        true,
        tooltip = "Logs an entry about a NPC that was just deleted from high resolution.",
        searchTerms = "npc,info,updating,npcs,update,del,deleting,remove,removing",
    ),
    NPC_MOVEMENT(
        SERVER_TO_CLIENT,
        INFO,
        "Npc Movement",
        true,
        tooltip = "Logs an entry about a NPC that was just crawled, walked, ran or teleported.",
        searchTerms = "npc,info,updating,npcs,update,movement,crawling,walking,running,ran,teleport",
    ),
    NPC_EXT_INFO(
        SERVER_TO_CLIENT,
        INFO,
        "Npc Ext. Info",
        true,
        tooltip = "Logs an entry about a NPC that had an extended info applied to them.",
        searchTerms = "npc,info,updating,npcs,update,extended,info,updating,masks",
    ),
    SET_NPC_UPDATE_ORIGIN(
        SERVER_TO_CLIENT,
        INFO,
        "Npc Info Origin",
        false,
        searchTerms = "npc,info,origin,relative,coordinate,update,updating",
    ),

    CLEAR_ENTITIES(
        SERVER_TO_CLIENT,
        INFO,
        "Clear Entities",
        true,
        searchTerms = "clear,entities,npcs,worldentities,worldentity",
    ),
    SET_ACTIVE_WORLD(
        SERVER_TO_CLIENT,
        INFO,
        "Active World",
        false,
        searchTerms = "set,active,worlds,worldentity,worldentities",
    ),
    WORLDENTITY_INFO(
        SERVER_TO_CLIENT,
        INFO,
        "World Entity Info",
        false,
        searchTerms = "worldentity,info,worlds,update,updating,sailing,ships",
    ),

    REBUILD(
        SERVER_TO_CLIENT,
        MAP,
        "Rebuild Map",
        false,
        searchTerms = "rebuild,normal,map,chunk,buildarea,mapsquare",
    ),

    VARP(
        SERVER_TO_CLIENT,
        ProtCategory.VARP,
        "Varps",
        true,
        searchTerms = "varp,varps,var,player,varbit,variables,32bit,integer",
    ),
    VARBITS(
        SERVER_TO_CLIENT,
        ProtCategory.VARP,
        "Varbits",
        true,
        searchTerms = "varbit,player,varbs,variables,varps",
    ),
    VARP_RESET(
        SERVER_TO_CLIENT,
        ProtCategory.VARP,
        "Varp Reset",
        true,
        searchTerms = "varp,reset,zeroing,varps,reset,login",
    ),
    VARP_SYNC(
        SERVER_TO_CLIENT,
        ProtCategory.VARP,
        "Varp Sync",
        true,
        searchTerms = "varps,synchronizing,client,server,",
    ),

    CAM_SHAKE(
        SERVER_TO_CLIENT,
        CAMERA,
        "Cam Shake",
        true,
        searchTerms = "camera,shake,shaking,effects",
    ),
    CAM_RESET(
        SERVER_TO_CLIENT,
        CAMERA,
        "Cam Reset",
        true,
        searchTerms = "camera,reset,resetting,stop",
    ),
    CAM_MOVETO(
        SERVER_TO_CLIENT,
        CAMERA,
        "Camera Movement",
        true,
        searchTerms = "camera,movement,moveto,face,point",
    ),
    CAM_LOOKAT(
        SERVER_TO_CLIENT,
        CAMERA,
        "Camera Turning",
        true,
        searchTerms = "camera,lookat,movement,turn,point",
    ),
    CAM_MODE(
        SERVER_TO_CLIENT,
        CAMERA,
        "Camera Mode",
        true,
        searchTerms = "camera,mode",
    ),
    CAM_TARGET(
        SERVER_TO_CLIENT,
        CAMERA,
        "Camera Target",
        false,
        searchTerms = "camera,target,focusing,sailing,ships",
    ),
    OCULUS_SYNC(
        SERVER_TO_CLIENT,
        CAMERA,
        "Oculus Sync",
        true,
        searchTerms = "orb,of,oculus,synchroniztion",
    ),

    UPDATE_INV(
        SERVER_TO_CLIENT,
        INVENTORIES,
        "Inventory Updates",
        true,
        searchTerms = "inventory,inventories,updating,items,objs,backpack,bank,equipment",
    ),

    MESSAGE_PRIVATE(
        SERVER_TO_CLIENT,
        MESSAGING,
        "Private Messages",
        false,
        searchTerms = "messages,messaging,private,dm,pm,social",
    ),
    FRIENDLIST_LOADED(
        SERVER_TO_CLIENT,
        SOCIAL,
        "Friendlist Loading",
        false,
        searchTerms = "friendlist,loaded,loading,friends,login",
    ),
    UPDATE_FRIENDLIST(
        SERVER_TO_CLIENT,
        SOCIAL,
        "Friendlist Updates",
        false,
        searchTerms = "friendlist,updates,friends,pm,dm",
    ),
    UPDATE_IGNORELIST(
        SERVER_TO_CLIENT,
        SOCIAL,
        "Ignorelist Updates",
        false,
        searchTerms = "ignorelist,ignores,update,updating",
    ),

    UPDATE_FRIENDCHAT_CHANNEL_FULL(
        SERVER_TO_CLIENT,
        FRIENDCHAT,
        "Friendchat Full Update",
        false,
        searchTerms = "friendchat,full,friends,clans,social,update",
    ),
    UPDATE_FRIENDCHAT_CHANNEL_SINGLEUSER(
        SERVER_TO_CLIENT,
        FRIENDCHAT,
        "Friendchat Single Update",
        false,
        searchTerms = "friendchat,clans,single,update,singleuser,social,friends",
    ),
    MESSAGE_FRIENDCHANNEL(
        SERVER_TO_CLIENT,
        FRIENDCHAT,
        "Friendchat Messages",
        false,
        searchTerms = "friendchat,messages,messaging,friends,clans,social",
    ),

    VARCLAN(
        SERVER_TO_CLIENT,
        CLAN,
        "Clan Vars",
        false,
        searchTerms = "variable,clans,varps,vars,channel",
    ),
    CLANCHANNEL(
        SERVER_TO_CLIENT,
        CLAN,
        "Clan Channel Updates",
        false,
        searchTerms = "clans,channel,updates,social",
    ),
    CLANSETTINGS(
        SERVER_TO_CLIENT,
        CLAN,
        "Clan Settings Updates",
        false,
        searchTerms = "clans,settings,updates,social",
    ),
    MESSAGE_CLANCHANNEL(
        SERVER_TO_CLIENT,
        CLAN,
        "Clan Messages",
        false,
        searchTerms = "message,clans,messaging,social,channel",
    ),

    LOGOUT(
        SERVER_TO_CLIENT,
        OTHER,
        "Logout",
        true,
        searchTerms = "logout,logging,out,stop",
    ),

    UPDATE_RUNWEIGHT(
        SERVER_TO_CLIENT,
        OTHER,
        "Weight",
        false,
        searchTerms = "update,run,weight,fat,slow,grams,kilos,pounds,stones,energy",
    ),
    UPDATE_RUNENERGY(
        SERVER_TO_CLIENT,
        OTHER,
        "Run Energy",
        false,
        searchTerms = "update,run,energy,fat,slow,energy,stamina",
    ),
    SET_MAP_FLAG(
        SERVER_TO_CLIENT,
        OTHER,
        "Minimap Flag",
        false,
        searchTerms = "minimap,set,flag,setflag,interacting,interaction",
    ),
    SET_PLAYER_OP(
        SERVER_TO_CLIENT,
        OTHER,
        "Player Menu Ops",
        true,
        searchTerms = "set,player,menu,options,ops,right,clicks",
    ),
    UPDATE_STAT(
        SERVER_TO_CLIENT,
        OTHER,
        "Stat Updates",
        true,
        searchTerms = "update,stats,skills,levels,experience",
    ),

    RUNCLIENTSCRIPT(
        SERVER_TO_CLIENT,
        OTHER,
        "Clientscripts",
        true,
        searchTerms = "run,clientscripts,cs2s,proc,script,interfaces,ifs",
    ),
    TRIGGER_ONDIALOGABORT(
        SERVER_TO_CLIENT,
        OTHER,
        "Dialog Abort",
        false,
        searchTerms = "dialogue,abort,closing,chatbox,ondialogabort,trigger",
    ),
    MESSAGE_GAME(
        SERVER_TO_CLIENT,
        MESSAGING,
        "Game Messages",
        true,
        searchTerms = "message,game,messaging,social,chat",
    ),
    CHAT_FILTER_SETTINGS(
        SERVER_TO_CLIENT,
        OTHER,
        "Chat Filter Settings",
        false,
        searchTerms = "chat,filter,settings,social,talking,chatting",
    ),
    UPDATE_STOCKMARKET_SLOT(
        SERVER_TO_CLIENT,
        OTHER,
        "Grand Exchange",
        true,
        searchTerms = "update,stockmarket,slot,grand,exchange,ge",
    ),
    ACCOUNT_FLAGS(
        StreamDirection.SERVER_TO_CLIENT,
        ProtCategory.OTHER,
        "Account Flags",
        true,
        searchTerms = "account,flags,accflags",
    ),

    HINT_ARROW(
        SERVER_TO_CLIENT,
        OTHER,
        "Hint Arrows",
        true,
        searchTerms = "hint,arrows,hintarrow,minimap,flashing",
    ),
    RESET_ANIMS(
        SERVER_TO_CLIENT,
        OTHER,
        "Reset Anims",
        false,
        searchTerms = "reset,animations,sequences,login,logout",
    ),
    UPDATE_REBOOT_TIMER(
        SERVER_TO_CLIENT,
        OTHER,
        "Reboot Timer",
        true,
        searchTerms = "update,reboot,timer,restart,game,logout",
    ),
    SET_HEATMAP_ENABLED(
        SERVER_TO_CLIENT,
        OTHER,
        "Heatmap",
        false,
        searchTerms = "set,heatmap,enabled,disabled,worldmap,java",
    ),
    MINIMAP_TOGGLE(
        SERVER_TO_CLIENT,
        OTHER,
        "Minimap Toggle",
        true,
        searchTerms = "set,minimap,toggle,hide,compass,unclickable",
    ),
    SERVER_TICK_END(
        SERVER_TO_CLIENT,
        OTHER,
        "Server Tick End",
        false,
        searchTerms = "server,tick,end,last,packet,ground,items,objs",
    ),
    HIDEOPS(
        SERVER_TO_CLIENT,
        OTHER,
        "Hide Entity Ops",
        true,
        searchTerms = "hide,entity,ops,locs,objs,items,npcs,options,cutscenes",
    ),
    SET_INTERACTION_MODE(
        SERVER_TO_CLIENT,
        OTHER,
        "Set Interaction Mode",
        true,
        searchTerms = "setinteractionmode,worldentity,ship",
    ),

    URL_OPEN(
        SERVER_TO_CLIENT,
        OTHER,
        "Url Open",
        false,
        searchTerms = "url,site,open,secure,link,browser",
    ),
    PACKET_GROUP(
        SERVER_TO_CLIENT,
        OTHER,
        "Packet Group",
        false,
        searchTerms = "packet,group,batch",
    ),
    ZBUF(
        SERVER_TO_CLIENT,
        OTHER,
        "ZBuf",
        true,
        searchTerms = "zbuf,depth,buffer",
    ),
    SITE_SETTINGS(
        SERVER_TO_CLIENT,
        OTHER,
        "Site Settings",
        false,
        searchTerms = "site,settings,uid192,random,data,authentication,linking",
    ),
    UPDATE_UID192(
        SERVER_TO_CLIENT,
        OTHER,
        "Uid 192",
        false,
        searchTerms = "uid192,update,random,data,authentication,linking",
    ),
    REFLECTION_CHECKER(
        SERVER_TO_CLIENT,
        OTHER,
        "Reflection Checks",
        false,
        searchTerms = "reflection,checks,java,bot,detection",
    ),
    SEND_PING(
        SERVER_TO_CLIENT,
        OTHER,
        "Ping",
        false,
        searchTerms = "send,ping,reply,timings",
    ),
    HISCORE_REPLY(
        SERVER_TO_CLIENT,
        OTHER,
        "Hiscore Reply",
        false,
        searchTerms = "hiscores,highscores,reply,stats,total,activities,activity",
    ),

    PLAYER_CHAT(
        SERVER_TO_CLIENT,
        PLAYER_EXTENDED_INFO,
        "Chat",
        false,
        searchTerms = "player,extended,info,updating,chat,talking,messages,messaging",
    ),
    PLAYER_FACE_ANGLE(
        SERVER_TO_CLIENT,
        PLAYER_EXTENDED_INFO,
        "Face Angle",
        true,
        searchTerms = "player,extended,info,updating,angle,facing,face,direction",
    ),
    PLAYER_MOVE_SPEED(
        SERVER_TO_CLIENT,
        PLAYER_EXTENDED_INFO,
        "Move Speed",
        false,
        searchTerms = "player,extended,info,movement,speeds,walk,run,crawl",
    ),
    PLAYER_NAME_EXTRAS(
        SERVER_TO_CLIENT,
        PLAYER_EXTENDED_INFO,
        "Name Extras",
        false,
        searchTerms = "player,extended,name,extras,before,after,combat,right,click,menu",
    ),
    PLAYER_SAY(
        SERVER_TO_CLIENT,
        PLAYER_EXTENDED_INFO,
        "Say",
        true,
        searchTerms = "player,extended,info,say,talk,overhead,chat,string",
    ),
    PLAYER_SEQUENCE(
        SERVER_TO_CLIENT,
        PLAYER_EXTENDED_INFO,
        "Sequence",
        true,
        searchTerms = "player,extended,info,sequence,animation",
    ),
    PLAYER_EXACTMOVE(
        SERVER_TO_CLIENT,
        PLAYER_EXTENDED_INFO,
        "Exact Move",
        true,
        searchTerms = "player,extended,info,exactmove,movement,agility,forcemove",
    ),
    PLAYER_HITS(
        SERVER_TO_CLIENT,
        PLAYER_EXTENDED_INFO,
        "Hits & Headbars",
        true,
        searchTerms = "player,extended,info,hits,headbars,hitmarks,healthbar,damage,timer",
    ),
    PLAYER_TINTING(
        SERVER_TO_CLIENT,
        PLAYER_EXTENDED_INFO,
        "Tinting",
        true,
        searchTerms = "player,extended,info,tinting,hue,saturation,lightness,nex",
    ),
    PLAYER_SPOTANIMS(
        SERVER_TO_CLIENT,
        PLAYER_EXTENDED_INFO,
        "Spotanims",
        true,
        searchTerms = "player,extended,info,spotanim,gfx,graphics,animations,sequences",
    ),
    PLAYER_FACE_PATHINGENTITY(
        SERVER_TO_CLIENT,
        PLAYER_EXTENDED_INFO,
        "Face Pathingentity",
        true,
        searchTerms = "player,extended,info,face,pathingentity,faceentity,locked,locking,focus",
    ),
    PLAYER_APPEARANCE(
        SERVER_TO_CLIENT,
        PLAYER_EXTENDED_INFO,
        "Appearance",
        true,
        searchTerms = "player,appearance,extended,info,name,level,combat,skill,equipment,models,mesh,identkit",
    ),
    PLAYER_APPEARANCE_DETAILS(
        SERVER_TO_CLIENT,
        PLAYER_EXTENDED_INFO,
        "Appearance: Details",
        true,
        searchTerms = "player,extended,info,appearance,details,name,level,combat,skill",
    ),
    PLAYER_APPEARANCE_STATUS(
        SERVER_TO_CLIENT,
        PLAYER_EXTENDED_INFO,
        "Appearance: Status",
        false,
        searchTerms = "player,extended,info,appearance,status",
    ),
    PLAYER_APPEARANCE_EQUIPMENT(
        SERVER_TO_CLIENT,
        PLAYER_EXTENDED_INFO,
        "Appearance: Equipment",
        false,
        searchTerms = "player,extended,info,appearance,equipment,items,objs",
    ),
    PLAYER_APPEARANCE_IDENTKIT(
        SERVER_TO_CLIENT,
        PLAYER_EXTENDED_INFO,
        "Appearance: Identkit",
        false,
        searchTerms = "player,extended,info,appearance,identkit,idk,identi,body",
    ),
    PLAYER_APPEARANCE_IF_IDENTKIT(
        SERVER_TO_CLIENT,
        PLAYER_EXTENDED_INFO,
        "Appearance: Interface Identkit",
        false,
        searchTerms = "player,extended,info,appearance,identkit,idk,identi,body,ifs,interfaces",
    ),
    PLAYER_APPEARANCE_COLOURS(
        SERVER_TO_CLIENT,
        PLAYER_EXTENDED_INFO,
        "Appearance: Colours",
        false,
        searchTerms = "player,extended,info,appearance,colors,colours",
    ),
    PLAYER_APPEARANCE_BAS(
        SERVER_TO_CLIENT,
        PLAYER_EXTENDED_INFO,
        "Appearance: Base Anim Set",
        false,
        searchTerms = "player,extended,info,appearance,sequences,seqs,animations,anims,base,set",
    ),
    PLAYER_APPEARANCE_NAME_EXTRAS(
        SERVER_TO_CLIENT,
        PLAYER_EXTENDED_INFO,
        "Appearance: Name Extras",
        false,
        searchTerms = "player,extended,info,appearance,name,extras,tags,burthrope,games,room",
    ),
    PLAYER_APPEARANCE_OBJ_TYPE_CUSTOMIZATION(
        SERVER_TO_CLIENT,
        PLAYER_EXTENDED_INFO,
        "Appearance: Obj Type Cust.",
        false,
        searchTerms = "player,extended,info,appearance,objs,type,customisation,customization,items,recolour,retexture",
    ),

    NPC_EXACTMOVE(
        SERVER_TO_CLIENT,
        NPC_EXTENDED_INFO,
        "Exact Move",
        true,
        searchTerms = "npcs,extended,info,exact,move,forcemove",
    ),
    NPC_FACE_PATHINGENTITY(
        SERVER_TO_CLIENT,
        NPC_EXTENDED_INFO,
        "Face Pathingentity",
        true,
        searchTerms = "npcs,extended,info,face,pathingentity,faceentity,facelock",
    ),
    NPC_HITS(
        SERVER_TO_CLIENT,
        NPC_EXTENDED_INFO,
        "Hits & Headbars",
        true,
        searchTerms = "npcs,extended,info,hits,hitmarks,headbars,healthbars,hitsplats",
    ),
    NPC_SAY(
        SERVER_TO_CLIENT,
        NPC_EXTENDED_INFO,
        "Say",
        true,
        searchTerms = "npcs,extended,info,chat,say,overhead,talk",
    ),
    NPC_SEQUENCE(
        SERVER_TO_CLIENT,
        NPC_EXTENDED_INFO,
        "Sequence",
        true,
        searchTerms = "npcs,extended,info,sequence,seqs,animations,anims",
    ),
    NPC_TINTING(
        SERVER_TO_CLIENT,
        NPC_EXTENDED_INFO,
        "Tinting",
        true,
        searchTerms = "npcs,extended,info,tinting,nex,hue,saturation,lightness",
    ),
    NPC_SPOTANIMS(
        SERVER_TO_CLIENT,
        NPC_EXTENDED_INFO,
        "Spotanims",
        true,
        searchTerms = "npcs,extended,info,spotanims,graphics,gfxs",
    ),
    NPC_BAS(
        SERVER_TO_CLIENT,
        NPC_EXTENDED_INFO,
        "Base Animation Set",
        true,
        searchTerms = "npcs,extended,info,base,animations,set,seqs,sequences",
    ),
    NPC_BODY_CUSTOMISATION(
        SERVER_TO_CLIENT,
        NPC_EXTENDED_INFO,
        "Body Customisation",
        true,
        searchTerms = "npcs,extended,info,body,customisation,customization,recolours,retextures",
    ),
    NPC_HEAD_CUSTOMISATION(
        SERVER_TO_CLIENT,
        NPC_EXTENDED_INFO,
        "Head Customisation",
        true,
        searchTerms = "npcs,extended,info,head,chathead,customisation,customization,recolours,retextures",
    ),
    NPC_LEVEL_CHANGE(
        SERVER_TO_CLIENT,
        NPC_EXTENDED_INFO,
        "Combat Level Change",
        true,
        searchTerms = "npcs,extended,info,combat,level,change",
    ),
    NPC_ENABLED_OPS(
        SERVER_TO_CLIENT,
        NPC_EXTENDED_INFO,
        "Enabled Ops",
        true,
        searchTerms = "npcs,extended,info,enabled,ops,options,right,click,menu",
    ),
    NPC_FACE_COORD(
        SERVER_TO_CLIENT,
        NPC_EXTENDED_INFO,
        "Face Coord",
        true,
        searchTerms = "npcs,extended,info,face,coords,coordinate,turn,look",
    ),
    NPC_NAME_CHANGE(
        SERVER_TO_CLIENT,
        NPC_EXTENDED_INFO,
        "Name Change",
        true,
        searchTerms = "npcs,extended,info,name,change,changing",
    ),
    NPC_TRANSFORMATION(
        SERVER_TO_CLIENT,
        NPC_EXTENDED_INFO,
        "Transformation",
        true,
        searchTerms = "npcs,extended,info,transformation,transmogrification,id,change,type",
    ),
    NPC_HEADICON_CUSTOMISATION(
        SERVER_TO_CLIENT,
        NPC_EXTENDED_INFO,
        "Headicon Customisation",
        true,
        searchTerms = "npcs,extended,info,headicons,prayer,overhead",
    ),

    DEPRECATED_CLIENT(
        CLIENT_TO_SERVER,
        DEPRECATED,
        "Deprecated",
        true,
        searchTerms = "deprecated,client",
    ),
    DEPRECATED_SERVER(
        SERVER_TO_CLIENT,
        DEPRECATED,
        "Deprecated",
        true,
        searchTerms = "deprecated,server",
    ),
}
