package net.rsprox.transcriber.prot

public enum class GameServerProt : Prot {
    // Interface related packets
    IF_RESYNC_V1,
    IF_RESYNC_V2,
    IF_OPENTOP,
    IF_OPENSUB,
    IF_CLOSESUB,
    IF_MOVESUB,
    IF_CLEARINV,
    IF_SETEVENTS_V1,
    IF_SETEVENTS_V2,
    IF_SETPOSITION,
    IF_SETSCROLLPOS,
    IF_SETROTATESPEED,
    IF_SETTEXT,
    IF_SETHIDE,
    IF_SETANGLE,
    IF_SETOBJECT,
    IF_SETCOLOUR,
    IF_SETANIM,
    IF_SETNPCHEAD,
    IF_SETNPCHEAD_ACTIVE,
    IF_SETPLAYERHEAD,
    IF_SETMODEL,
    IF_SETPLAYERMODEL_BASECOLOUR,
    IF_SETPLAYERMODEL_BODYTYPE,
    IF_SETPLAYERMODEL_OBJ,
    IF_SETPLAYERMODEL_SELF,

    // Music-system related packets (excl. zone ones)
    MIDI_SONG_V2,
    MIDI_SONG_WITHSECONDARY,
    MIDI_SWAP,
    MIDI_SONG_STOP,
    MIDI_SONG_V1,
    MIDI_JINGLE,
    SYNTH_SOUND,

    // Zone header packets
    UPDATE_ZONE_FULL_FOLLOWS,
    UPDATE_ZONE_PARTIAL_FOLLOWS,
    UPDATE_ZONE_PARTIAL_ENCLOSED,

    // Zone payload packets
    LOC_ADD_CHANGE_V1,
    LOC_ADD_CHANGE_V2,
    LOC_DEL,
    LOC_ANIM,
    LOC_MERGE,
    OBJ_ADD,
    OBJ_DEL,
    OBJ_COUNT,
    OBJ_ENABLED_OPS,
    OBJ_CUSTOMISE,
    OBJ_UNCUSTOMISE,
    MAP_ANIM,
    MAP_PROJANIM_V1,
    MAP_PROJANIM_V2,
    SOUND_AREA,

    // Specific packets
    PROJANIM_SPECIFIC_V4,
    PROJANIM_SPECIFIC_V3,
    PROJANIM_SPECIFIC_V2,
    PROJANIM_SPECIFIC_V1,
    MAP_ANIM_SPECIFIC,
    LOC_ANIM_SPECIFIC,
    NPC_HEADICON_SPECIFIC,
    NPC_SPOTANIM_SPECIFIC,
    NPC_ANIM_SPECIFIC,
    PLAYER_ANIM_SPECIFIC,
    PLAYER_SPOTANIM_SPECIFIC,
    OBJ_ADD_SPECIFIC,
    OBJ_DEL_SPECIFIC,
    OBJ_ENABLED_OPS_SPECIFIC,
    OBJ_UNCUSTOMISE_SPECIFIC,
    OBJ_COUNT_SPECIFIC,
    OBJ_CUSTOMISE_SPECIFIC,

    // Info packets
    PLAYER_INFO,
    NPC_INFO_SMALL_V5,
    NPC_INFO_LARGE_V5,
    NPC_INFO_SMALL_V4,
    NPC_INFO_LARGE_V4,
    SET_NPC_UPDATE_ORIGIN,

    // World entity packets
    CLEAR_ENTITIES,
    SET_ACTIVE_WORLD_V2,
    SET_ACTIVE_WORLD_V1,
    WORLDENTITY_INFO_V6,
    WORLDENTITY_INFO_V5,
    WORLDENTITY_INFO_V4,
    WORLDENTITY_INFO_V3,
    WORLDENTITY_INFO_V2,
    WORLDENTITY_INFO_V1,

    // Map packets
    REBUILD_NORMAL,
    REBUILD_REGION,
    REBUILD_WORLDENTITY_V3,
    REBUILD_WORLDENTITY_V2,
    REBUILD_WORLDENTITY_V1,

    // Varp packets
    VARP_SMALL,
    VARP_LARGE,
    VARP_RESET,
    VARP_SYNC,

    // Camera packets
    CAM_SHAKE,
    CAM_RESET,
    CAM_SMOOTHRESET,
    CAM_MOVETO,
    CAM_MOVETO_CYCLES,
    CAM_MOVETO_ARC,
    CAM_LOOKAT,
    CAM_LOOKAT_EASED_COORD,
    CAM_ROTATEBY,
    CAM_ROTATETO,
    CAM_MODE,
    CAM_TARGET_V3,
    CAM_TARGET_V2,
    CAM_TARGET_V1,
    OCULUS_SYNC,

    // Inventory packets
    UPDATE_INV_FULL,
    UPDATE_INV_PARTIAL,
    UPDATE_INV_STOPTRANSMIT,

    // Social packets
    MESSAGE_PRIVATE,
    MESSAGE_PRIVATE_ECHO,
    FRIENDLIST_LOADED,
    UPDATE_FRIENDLIST,
    UPDATE_IGNORELIST,

    // Friend chat (old "clans") packets
    UPDATE_FRIENDCHAT_CHANNEL_FULL_V1,
    UPDATE_FRIENDCHAT_CHANNEL_FULL_V2,
    UPDATE_FRIENDCHAT_CHANNEL_SINGLEUSER,
    MESSAGE_FRIENDCHANNEL,

    // Clan chat packets
    VARCLAN,
    VARCLAN_ENABLE,
    VARCLAN_DISABLE,
    CLANCHANNEL_FULL,
    CLANCHANNEL_DELTA,
    CLANSETTINGS_FULL,
    CLANSETTINGS_DELTA,
    MESSAGE_CLANCHANNEL,
    MESSAGE_CLANCHANNEL_SYSTEM,

    // Log out packets
    LOGOUT,
    LOGOUT_WITHREASON,
    LOGOUT_TRANSFER,

    // Misc. player state packets
    UPDATE_RUNWEIGHT,
    UPDATE_RUNENERGY,
    SET_MAP_FLAG,
    SET_PLAYER_OP,
    UPDATE_STAT_V2,
    UPDATE_STAT_V1,

    // Misc. player packets
    RUNCLIENTSCRIPT,
    TRIGGER_ONDIALOGABORT,
    MESSAGE_GAME,
    CHAT_FILTER_SETTINGS,
    CHAT_FILTER_SETTINGS_PRIVATECHAT,
    UPDATE_TRADINGPOST,
    UPDATE_STOCKMARKET_SLOT,
    ACCOUNT_FLAGS,

    // Misc. client state packets
    HINT_ARROW,
    RESET_ANIMS,
    UPDATE_REBOOT_TIMER,
    SET_HEATMAP_ENABLED,
    MINIMAP_TOGGLE,
    SERVER_TICK_END,
    HIDENPCOPS,
    HIDEOBJOPS,
    HIDELOCOPS,
    SET_INTERACTION_MODE,
    RESET_INTERACTION_MODE,

    // Misc. client packets
    URL_OPEN,
    SITE_SETTINGS,
    UPDATE_UID192,
    REFLECTION_CHECKER,
    SEND_PING,
    HISCORE_REPLY,
    PACKET_GROUP_START,
    PACKET_GROUP_END,

    // Unknown packets
    UNKNOWN_STRING,

    RECONNECT,
}
