package net.rsprox.transcriber.prot

public enum class GameClientProt : Prot {
    // If buttons
    IF_BUTTON,
    IF_BUTTON1,
    IF_BUTTON2,
    IF_BUTTON3,
    IF_BUTTON4,
    IF_BUTTON5,
    IF_BUTTON6,
    IF_BUTTON7,
    IF_BUTTON8,
    IF_BUTTON9,
    IF_BUTTON10,
    IF_SUBOP,
    IF_BUTTOND,
    IF_BUTTONT,

    // Op npc
    OPNPC1,
    OPNPC2,
    OPNPC3,
    OPNPC4,
    OPNPC5,
    OPNPC6,
    OPNPCT,
    OPNPCU,

    // Op loc
    OPLOC1,
    OPLOC2,
    OPLOC3,
    OPLOC4,
    OPLOC5,
    OPLOC6,
    OPLOCT,
    OPLOCU,

    // Op obj
    OPOBJ1,
    OPOBJ2,
    OPOBJ3,
    OPOBJ4,
    OPOBJ5,
    OPOBJ6,
    OPOBJT,
    OPOBJU,

    // Op player
    OPPLAYER1,
    OPPLAYER2,
    OPPLAYER3,
    OPPLAYER4,
    OPPLAYER5,
    OPPLAYER6,
    OPPLAYER7,
    OPPLAYER8,
    OPPLAYERT,
    OPPLAYERU,

    // Op held
    OPHELD6,

    // Events
    EVENT_APPLET_FOCUS,
    EVENT_CAMERA_POSITION,
    EVENT_KEYBOARD,
    EVENT_MOUSE_SCROLL,
    EVENT_MOUSE_MOVE,
    EVENT_NATIVE_MOUSE_MOVE,
    EVENT_MOUSE_CLICK,
    EVENT_NATIVE_MOUSE_CLICK,

    // Resume events
    RESUME_PAUSEBUTTON,
    RESUME_P_NAMEDIALOG,
    RESUME_P_STRINGDIALOG,
    RESUME_P_COUNTDIALOG,
    RESUME_P_OBJDIALOG,

    // Friend chat packets
    FRIENDCHAT_KICK,
    FRIENDCHAT_SETRANK,
    FRIENDCHAT_JOIN_LEAVE,

    // Clan packets
    CLANCHANNEL_FULL_REQUEST,
    CLANSETTINGS_FULL_REQUEST,
    CLANCHANNEL_KICKUSER,
    AFFINEDCLANSETTINGS_ADDBANNED_FROMCHANNEL,
    AFFINEDCLANSETTINGS_SETMUTED_FROMCHANNEL,

    // Socials
    FRIENDLIST_ADD,
    FRIENDLIST_DEL,
    IGNORELIST_ADD,
    IGNORELIST_DEL,

    // Messaging
    MESSAGE_PUBLIC,
    MESSAGE_PRIVATE,

    // Misc. user packets
    MOVE_GAMECLICK,
    MOVE_MINIMAPCLICK,
    CLIENT_CHEAT,
    SET_CHATFILTERSETTINGS,
    CLICKWORLDMAP,
    OCULUS_LEAVE,
    CLOSE_MODAL,
    TELEPORT,
    BUG_REPORT,
    SEND_SNAPSHOT,
    HISCORE_REQUEST,
    IF_CRMVIEW_CLICK,
    UPDATE_PLAYER_MODEL_V2,
    UPDATE_PLAYER_MODEL_V1,

    // Misc. client packets
    CONNECTION_TELEMETRY,
    SEND_PING_REPLY,
    DETECT_MODIFIED_CLIENT,
    REFLECTION_CHECK_REPLY,
    NO_TIMEOUT,
    IDLE,
    MAP_BUILD_COMPLETE,
    MEMBERSHIP_PROMOTION_ELIGIBILITY,
    SOUND_JINGLEEND,
    WINDOW_STATUS,
    SET_HEADING,
}
