package net.rsprox.protocol.rs3.game.incoming.model.events

import net.rsprot.protocol.ClientProtCategory
import net.rsprot.protocol.message.IncomingGameMessage
import net.rsprox.protocol.game.incoming.model.GameClientProtCategory

public data class ClientDetailOptionsStatus(
    public val version: Int,
    public val compatibility1: Int,
    public val compatibility2: Int,
    public val setting0: Int,
    public val setting1: Int,
    public val setting2: Int,
    public val compatibility6: Int,
    public val setting3: Int,
    public val setting4: Int,
    public val compatibility9: Int,
    public val setting5: Int,
    public val setting6: Int,
    public val compatibility12: Int,
    public val compatibility13: Int,
    public val compatibility14: Int,
    public val setting7: Int,
    public val compatibility16: Int,
    public val compatibility17: Int,
    public val compatibility18: Int,
    public val setting8: Int,
    public val compatibility20: Int,
    public val compatibility21: Int,
    public val compatibility22: Int,
    public val setting9: Int,
    public val compatibility24: Int,
    public val compatibility25: Int,
    public val compatibility26: Int,
    public val setting10: Int,
    public val setting11: Int,
    public val setting12: Int,
    public val setting13: Int,
    public val setting14: Int,
    public val setting15: Int,
    public val setting16: Int,
    public val setting17: Int,
    public val setting18: Int,
    public val setting19: Int,
    public val setting20: Int,
    public val setting21: Int,
    public val setting22: Int,
    public val setting23: Int,
    public val setting24: Int,
    public val compatibility46: Int,
    public val compatibility47: Int,
    public val compatibility48: Int,
    public val compatibility49: Int,
    public val compatibility50: Int,
    public val compatibility51: Int,
    public val setting25: Int,
    public val setting26: Int,
    public val setting27: Int,
    public val setting28: Int,
    public val setting29: Int,
    public val compatibility57: Int,
) : IncomingGameMessage {
    override val category: ClientProtCategory
        get() = GameClientProtCategory.CLIENT_EVENT
}
